# Generated by Django 5.2.3 on 2025-07-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_dated',
            new_name='published_date',
        ),
    ]
